using System;

namespace Niflib
{
	public enum eTexFilterMode : uint
	{
		FILTER_NEAREST,
		FILTER_BILERP,
		FILTER_TRILERP,
		FILTER_NEAREST_MIPNEAREST,
		FILTER_NEAREST_MIPLERP,
		FILTER_BILERP_MIPNEAREST
	}
}
